# 模组加载器设置
modLoader="javafml" #必须
loaderVersion="${loader_version_range}" #必须 - 加载器版本范围

# 模组基本信息
license="LGPL" #许可证
[[mods]] #模组定义开始 - 必须
modId="mobackup" #必须 - 模组ID
version="${mod_version}" #必须 - 模组版本
displayName="MoreBackpackUpgrades" #必须 - 模组显示名称
authors="空枝霁雨" #可选 - 作者
description='''为精妙背包和精致存储添加了联动物品''' # 模组描述

# 依赖项配置
[[dependencies.${mod_id}]] #Forge依赖
modId="forge"
mandatory=true #必须 - 是否强制需要
versionRange="[47.4.0,)" #必须 - Forge版本范围
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]] #Minecraft依赖
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

# 这里添加依赖
[[dependencies.mobackup]]
modId="refinedstorage"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.mobackup]]
modId="sophisticatedcore"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.mobackup]]
modId="sophisticatedbackpacks"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"
